#!/bin/bash

if [ "$1" = "--help" ] ; then
	echo "Pomoci getmedia lze v html souboru nalezt odkazy na obrazky a zvuky"
	echo "Getmedia prijima jediny parametr, a to jmeno html souboru, ve kterem ma hledat"
	echo "-i zobrazi jen odkazy na obrazky"
	echo "-s zobrazi jen odkazy na zvuky"

elif [ "$1" = "-s" ] ; then 
	cat $2 | grep -oE "href=\"[^=]*.[wmo][pag][gv3]\"" | sed 's/\"//g' | sed 's/^.....//g'
	cat $2 | grep -oE "src=\"[^=]*.[wmo][pag][gv3]\"" | sed 's/\"//g' | sed 's/^....//g'


elif [ "$1" = "-i" ] ; then
	cat $2 | grep -oE "href=\"[^=]*.[jps][pnv][g]\"" | sed 's/\"//g' | sed 's/^.....//g'
	cat $2 | grep -oE "src=\"[^=]*.[jps][pnv][g]\"" | sed 's/\"//g' | sed 's/^....//g'
		
else
        cat $1 | grep -oE "href=\"[^=]*.[\/]*[jpswmo][pnvag][gv3]\"" | sed 's/\"//g' | sed 's/^.....//g' 
	cat $1 | grep -oE "src=\"[^=]*.[\/]*[jpswmo][pnvag][gv3]\"" | sed 's/\"//g' | sed 's/^....//g'
fi


